-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Customer"
(
    customer_id integer NOT NULL,
    customer_name character varying COLLATE pg_catalog."default",
    age integer,
    gender character varying(1) COLLATE pg_catalog."default",
    address character varying COLLATE pg_catalog."default",
    phone numeric,
    CONSTRAINT "Customer_pkey" PRIMARY KEY (customer_id)
);

CREATE TABLE IF NOT EXISTS public."Location"
(
    location_id integer NOT NULL,
    country character varying COLLATE pg_catalog."default",
    city character varying COLLATE pg_catalog."default",
    province character varying COLLATE pg_catalog."default",
    district character varying COLLATE pg_catalog."default",
    CONSTRAINT "Location_pkey" PRIMARY KEY (location_id)
);

CREATE TABLE IF NOT EXISTS public."Payment"
(
    payment_id integer NOT NULL,
    payment_type character varying COLLATE pg_catalog."default",
    payment_discount character varying COLLATE pg_catalog."default",
    CONSTRAINT "Payment_pkey" PRIMARY KEY (payment_id)
);

CREATE TABLE IF NOT EXISTS public."Product"
(
    product_id integer NOT NULL,
    product_name character varying COLLATE pg_catalog."default",
    product_price integer,
    CONSTRAINT "Product_pkey" PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public."Sales"
(
    sales_id integer NOT NULL,
    product_id integer,
    location_id integer,
    time_id integer,
    payment_id integer,
    customer_id integer,
    CONSTRAINT "Sales_pkey" PRIMARY KEY (sales_id)
);

CREATE TABLE IF NOT EXISTS public."Time"
(
    time_id integer NOT NULL,
    year integer,
    month integer,
    day integer,
    hour integer,
    CONSTRAINT "Time_pkey" PRIMARY KEY (time_id)
);

ALTER TABLE IF EXISTS public."Sales"
    ADD CONSTRAINT customer_id FOREIGN KEY (customer_id)
    REFERENCES public."Customer" (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Sales"
    ADD CONSTRAINT location_id FOREIGN KEY (location_id)
    REFERENCES public."Location" (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Sales"
    ADD CONSTRAINT payment_id FOREIGN KEY (payment_id)
    REFERENCES public."Payment" (payment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Sales"
    ADD CONSTRAINT product_id FOREIGN KEY (product_id)
    REFERENCES public."Product" (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Sales"
    ADD CONSTRAINT time_id FOREIGN KEY (time_id)
    REFERENCES public."Time" (time_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;